### ISSUE TITLE
Postman integration is not working on ReadyAPI3.3.0

### ISSUE THREAD

**Issue by nfactorial-barcelona** [SmartBear/readyapi-postman-plugin#23]
Installing the integration ReadyAPI Postman Plugin version 2.0.0 you can't create a new postman project in ReadyAPI 3.0.0. - SOAPUI PRO

![Captura de pantalla 2020-02-04 a las 18 57 05](https://user-images.githubusercontent.com/60666576/73772277-275cca80-4780-11ea-9869-a1db43dc9108.png)

It's not possible to find the option in the menu.

**Comment by Alexander-Sviridov** [comment]
Hi, @nfactorial-barcelona!

Please note that Postman collection isn't a definition. In 3.0.0 once the plugin is installed you'll see the appropriate link on the Integration tab of this dialog. Now it is in the correct place.

**Comment by nfactorial-barcelona** [comment]
Hola @Alexander-Sviridov 

Yes! . You can import from integration tap on the new project dialog.

Thanks for your support!

**Comment by Alexander-Sviridov** [comment]
@nfactorial-barcelona, you are welcome!
